services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitness_training_app
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=fitness_training_dev;Username=postgres;Password=abracadabra
    ports:
      - "5127:8080"
    volumes:
      - fitness_training_uploads:/app/wwwroot/uploads
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: fitness_training_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fitness_training_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abracadabra
    ports:
      - "5433:5432"
    volumes:
      - fitness_training_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fitness_training_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  fitness_training_postgres_data:
  fitness_training_uploads:
